### ISSUE TITLE
sever stoped?

### ISSUE THREAD

**Issue by leoking0424** [cpinitiative/ide#154]
the ide server stopped

**Comment by ericshu6** [comment]
yeah me too!

**Comment by thecodingwizard** [comment]
sorry, I rebooted it and it should work now. Thanks for reporting this!

```
Node.js v18.14.2
node:events:491
      throw er; // Unhandled 'error' event
      ^

RangeError: Max payload size exceeded
    at Receiver.haveLength (/home/ideyjs/ide-yjs/node_modules/ws/lib/receiver.js:292:16)
    at Receiver.getPayloadLength64 (/home/ideyjs/ide-yjs/node_modules/ws/lib/receiver.js:278:17)
    at Receiver.startLoop (/home/ideyjs/ide-yjs/node_modules/ws/lib/receiver.js:132:22)
    at Receiver._write (/home/ideyjs/ide-yjs/node_modules/ws/lib/receiver.js:74:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.socketOnData (/home/ideyjs/ide-yjs/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/home/ideyjs/ide-yjs/node_modules/ws/lib/websocket.js:769:13)
    at Receiver.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  [Symbol(status-code)]: 1009
}
```

**Comment by leoking0424** [comment]
thanks
